project_id = "dicwdviufetibnafzipa"

[functions.rid-ai-coach]
verify_jwt = false

[functions.mydata-send-receipt]
verify_jwt = false

[functions.mark-missed-workouts]
verify_jwt = false

[functions.force-missed-workouts]
verify_jwt = false

[functions.send-offer-notifications]
verify_jwt = false

[functions.magic-box-draw]
verify_jwt = true

[functions.magic-box-open]
verify_jwt = false

[functions.create-magic-boxes]
verify_jwt = false

[functions.analyze-school-note]
verify_jwt = false

[functions.send-rpe-notification]
verify_jwt = false